name: WarpPlugin
main: com.joshcough.minecraft.examples.WarpPlugin
author: Josh Cough
version: 0.1
api-version: 1.13
depend: [ScalaLibPlugin, ScalaPluginAPI]
softdepend: []
commands:
  warps:
    description: List all warps.
    usage: /warps EOF
  warp:
    description: Warp to the given warp location.
    usage: /warp warp-name
  set-warp:
    description: Create a new warp location.
    usage: /set-warp warp-name
  delete-warp:
    description: Delete a warp.
    usage: /delete-warp warp-name
  home:
    description: Warp home.
    usage: /home EOF
  set-home:
    description: Set your home location.
    usage: /set-home EOF
  delete-home:
    description: Delete your home location.
    usage: /delete-home EOF
  delete-all:
    description: Delete all your warps.
    usage: /delete-all EOF